### PR TITLE
Update for query branch

### PR DESCRIPTION
**Pull request by jackzampolin**

### CODE REVIEW

**Comment by jackzampolin** [comment]
Blocked on https://github.com/cosmos/cosmos-sdk/pull/5901

**Comment by jackzampolin** [comment]
This PR is blocked on:

- [ ] Resolving the opaque packet verification issue
- [ ] Fixing the transfer commands to accommodate the `source` change

It also contains some work to prepare the ground for the query work to navigate between chains. Going to need some help from @cwgoes and @AdityaSripal here.

**Comment by jackzampolin** [comment]
On the path negotiation side, I have a `rly paths find` command that queries all of the configured chains and returns all the paths between them. Needed functionality:
- [ ] `rly pth find-or-gen [src-chain-id] [dst-chain-id] [src-port-id] [dst-port-id] [name]` - Uses any existing primitives found on src or dst to create a path between two ports.
- [ ] `pathA.Equal(pathB)` needed to deduplicate existing paths in the config

**Comment by cwgoes** [comment]
What is the opaque packet verification issue? Are certain `verifyMembership` calls failing which didn't previously, or something like that? Theoretically the SDK-side test-cases should cover this.

**Pull request merged**
