### PR TITLE
Add vitwitchain-1 conf

### PR DESCRIPTION
**Pull request by anilcse**

### CODE REVIEW

**Comment by jackzampolin** [comment]
Getting an error trying to initialize the lite client here:
```
I[2020-03-20|10:14:53.109] Downloading trusted header using options     
Error: signedHeader header and commit height mismatch: 771 vs 0
```

**Comment by anilCSE** [comment]
> Getting an error trying to initialize the lite client here:
> 
> ```
> I[2020-03-20|10:14:53.109] Downloading trusted header using options     
> Error: signedHeader header and commit height mismatch: 771 vs 0
> ```

This might be the issue: #25

**Comment by anilcse** [comment]
init is fixed but faucet is not working due to #25

**Comment by jackzampolin** [comment]
I've got this working with https://github.com/iqlusioninc/relayer/pull/46. Welcome to the IBC testnet! 🎉 :party_parrot:

**Pull request merged**
