### PR TITLE
Respect the `override` flag upon client creation

### PR DESCRIPTION
**Pull request by jtieri**
Previously we were not checking if the `--override` flag was set and so if a user had an existing client configured for a particular path and then attempted to create a new client it would always return immediately after the call to `QueryClientStateResponse`

Now if a user has specified `--override` it will attempt to create a new client regardless of if there is already a client configured. The new client ID will be written to the config file upon completion.

### CODE REVIEW

**Comment by mark-rushakoff** [comment]
Does it make sense to add a test for use of the --override flag?

**Comment by jtieri** [comment]
> Does it make sense to add a test for use of the --override flag?

I think so, at least it ensures there are no regressions around this behavior. I'll get a test pushed up will re-ping for review.

**Review by mark-rushakoff — APPROVED** [review]
New test looks good, thanks.

**Comment by jtieri** [comment]
I'm going to merge this because it does fix the issue of the `--override` flag not being respected, however, there is an issue with finding a matching light client still. A fix for this is outside the scope of this PR and is being tracked here #1006

**Pull request merged**
