### PR TITLE
Properly Unlock SDKConfig

### PR DESCRIPTION
**Pull request by AdityaSripal**

### CODE REVIEW

**Comment by AdityaSripal** [comment]
```
relayer git:(aditya/testing) ✗ rly tx link demo -d -o 3s       
I[2020-10-21|18:03:02.580] - [stargate-4] -> creating client (sleepsrcclient) for [slippy-0]header-height{104045} trust-period(160h0m0s) 
I[2020-10-21|18:03:02.766] - [slippy-0] -> creating client (sleepdstclient) for [stargate-4]header-height{95478} trust-period(336h0m0s) 
I[2020-10-21|18:03:05.268] ✔ [stargate-4]@{95479} - msg(0:create_client) hash(BA8A9C647DBF7C2D90F2424ED3F57617731046461BDB68B7BC2D1C7312A9650B) 
I[2020-10-21|18:03:06.956] ✔ [slippy-0]@{104046} - msg(0:create_client) hash(1C89BA65D14264D9EC0E18D663F1AAEAA55B9116D4047442899AA6961E04EF2B) 
I[2020-10-21|18:03:06.956] ★ Clients created: [stargate-4]client(sleepsrcclient) and [slippy-0]client(sleepdstclient) 
try unlock
unlocked
try unlock
Query HistoricalInfo
unlocked
Query HistoricalInfo
I[2020-10-21|18:03:08.842] - [stargate-4]@{0}conn(sleepsrcconn)-{STATE_UNINITIALIZED_UNSPECIFIED} : [slippy-0]@{0}conn(sleepdstconn)-{STATE_UNINITIALIZED_UNSPECIFIED} 
I[2020-10-21|18:03:11.779] ✔ [stargate-4]@{95480} - msg(0:connection_open_init) hash(0305E4D1E0B0288C6D9212BDDAC6E658BF7AFC6238A6B374A28106E3BAFE5E13) 
try unlock
unlocked
try unlock
Query HistoricalInfo
unlocked
Query HistoricalInfo
I[2020-10-21|18:03:12.553] - [stargate-4]@{0}conn(sleepsrcconn)-{STATE_UNINITIALIZED_UNSPECIFIED} : [slippy-0]@{0}conn(sleepdstconn)-{STATE_UNINITIALIZED_UNSPECIFIED} 
I[2020-10-21|18:03:13.023] - [stargate-4] -> sending transaction:       
E[2020-10-21|18:03:13.024] - [stargate-4] -> err(failed to execute message; message index: 0: connection handshake open init failed: sleepsrcconn: connection already exists: invalid request) 
I[2020-10-21|18:03:13.024] retrying transaction...                      
try unlock
unlocked
try unlock
Query HistoricalInfo
unlocked
Query HistoricalInfo
I[2020-10-21|18:03:19.268] - [slippy-0]@{0}conn(sleepdstconn)-{STATE_UNINITIALIZED_UNSPECIFIED} : [stargate-4]@{95481}conn(sleepsrcconn)-{STATE_INIT} 
I[2020-10-21|18:03:21.984] ✔ [slippy-0]@{104049} - msg(0:update_client,1:connection_open_try) hash(F6687BECA63A93DE158D1BA664794D020E2006E4319893B28CC72A80FC385F9D) 
try unlock
unlocked
try unlock
Query HistoricalInfo
unlocked
Query HistoricalInfo
I[2020-10-21|18:03:23.214] - [slippy-0]@{0}conn(sleepdstconn)-{STATE_UNINITIALIZED_UNSPECIFIED} : [stargate-4]@{95481}conn(sleepsrcconn)-{STATE_INIT} 
I[2020-10-21|18:03:23.403] - [slippy-0] -> sending transaction:         
E[2020-10-21|18:03:23.403] - [slippy-0] -> err(failed to execute message; message index: 1: connection handshake open try failed: cannot relay connection attempt: invalid connection: invalid request) 
I[2020-10-21|18:03:23.403] retrying transaction...                      
try unlock
unlocked
try unlock
Query HistoricalInfo
unlocked
Query HistoricalInfo
I[2020-10-21|18:03:29.674] - [stargate-4]@{95482}conn(sleepsrcconn)-{STATE_INIT} : [slippy-0]@{104050}conn(sleepdstconn)-{STATE_TRYOPEN} 
I[2020-10-21|18:03:35.845] ✔ [stargate-4]@{95484} - msg(0:update_client,1:connection_open_ack) hash(6B3166E4AB62865084325974A3D3A2631213CEC52AD58541D33E21DFD6CF06CB) 
try unlock
unlocked
try unlock
Query HistoricalInfo
unlocked
Query HistoricalInfo
I[2020-10-21|18:03:37.084] - [stargate-4]@{95484}conn(sleepsrcconn)-{STATE_INIT} : [slippy-0]@{104051}conn(sleepdstconn)-{STATE_TRYOPEN} 
I[2020-10-21|18:03:37.676] - [stargate-4] -> sending transaction:       
E[2020-10-21|18:03:37.676] - [stargate-4] -> err(failed to execute message; message index: 1: connection handshake open ack failed: connection state is not INIT or TRYOPEN (got STATE_OPEN): invalid connection state: invalid request) 
I[2020-10-21|18:03:37.676] retrying transaction...                      
try unlock
unlocked
try unlock
Query HistoricalInfo
unlocked
Query HistoricalInfo
I[2020-10-21|18:03:43.924] - [slippy-0]@{104053}conn(sleepdstconn)-{STATE_TRYOPEN} : [stargate-4]@{95485}conn(sleepsrcconn)-{STATE_OPEN} 
I[2020-10-21|18:03:47.031] ✔ [slippy-0]@{104054} - msg(0:update_client,1:connection_open_confirm) hash(18C6FE9EA5A6450E07529D00B48222D6D9FC01DBF333D2DE93F93F84E3D515E6) 
I[2020-10-21|18:03:47.301] - [stargate-4]@{0}conn(sleepsrcconn)-{STATE_UNINITIALIZED_UNSPECIFIED} : [slippy-0]@{0}conn(sleepdstconn)-{STATE_UNINITIALIZED_UNSPECIFIED} 
I[2020-10-21|18:03:47.301] ★ Connection created: [stargate-4]client{sleepsrcclient}conn{sleepsrcconn} -> [slippy-0]client{sleepdstclient}conn{sleepdstconn} 
try unlock
unlocked
try unlock
Query HistoricalInfo
unlocked
Query HistoricalInfo
I[2020-10-21|18:03:48.070] - [stargate-4]@{0}chan(sleepsrcchan)-{STATE_UNINITIALIZED_UNSPECIFIED} : [slippy-0]@{0}chan(sleepdstchan)-{STATE_UNINITIALIZED_UNSPECIFIED} 
I[2020-10-21|18:03:53.255] ✔ [stargate-4]@{95487} - msg(0:channel_open_init) hash(EBE19C0E2824622BAE83F2F6AC8DE3D2FC44D2889692690D46FDF0806D7B9A08) 
try unlock
unlocked
try unlock
Query HistoricalInfo
unlocked
Query HistoricalInfo
I[2020-10-21|18:03:54.026] - [stargate-4]@{0}chan(sleepsrcchan)-{STATE_UNINITIALIZED_UNSPECIFIED} : [slippy-0]@{0}chan(sleepdstchan)-{STATE_UNINITIALIZED_UNSPECIFIED} 
I[2020-10-21|18:03:54.492] - [stargate-4] -> sending transaction:       
E[2020-10-21|18:03:54.492] - [stargate-4] -> err(failed to execute message; message index: 0: channel handshake open init failed: port ID (transfer) channel ID (sleepsrcchan): channel already exists: invalid request) 
I[2020-10-21|18:03:54.492] retrying transaction...                      
try unlock
unlocked
try unlock
Query HistoricalInfo
unlocked
Query HistoricalInfo
I[2020-10-21|18:04:00.264] - [slippy-0]@{0}chan(sleepdstchan)-{STATE_UNINITIALIZED_UNSPECIFIED} : [stargate-4]@{95488}chan(sleepsrcchan)-{STATE_INIT} 
I[2020-10-21|18:04:02.159] ✔ [slippy-0]@{104057} - msg(0:update_client,1:channel_open_try) hash(DE9A816E744B3A11844401B9EF8CF8E40168E1315B545D671F2BA3B3544133C0) 
try unlock
unlocked
try unlock
Query HistoricalInfo
unlocked
Query HistoricalInfo
I[2020-10-21|18:04:03.074] - [slippy-0]@{0}chan(sleepdstchan)-{STATE_UNINITIALIZED_UNSPECIFIED} : [stargate-4]@{95488}chan(sleepsrcchan)-{STATE_INIT} 
I[2020-10-21|18:04:03.263] - [slippy-0] -> sending transaction:         
E[2020-10-21|18:04:03.264] - [slippy-0] -> err(failed to execute message; message index: 1: channel handshake open try failed: cannot relay connection attempt: invalid channel: invalid request) 
I[2020-10-21|18:04:03.264] retrying transaction...                      
try unlock
unlocked
try unlock
Query HistoricalInfo
unlocked
Query HistoricalInfo
I[2020-10-21|18:04:09.039] - [stargate-4]@{95489}chan(sleepsrcchan)-{STATE_INIT} : [slippy-0]@{104058}chan(sleepdstchan)-{STATE_TRYOPEN} 
I[2020-10-21|18:04:11.456] ✔ [stargate-4]@{95490} - msg(0:update_client,1:channel_open_ack) hash(5B19127374B4514CD0D1029A8B7C9C7B20705EFE545A59BDFC0115E640B8EB3D) 
try unlock
unlocked
try unlock
Query HistoricalInfo
unlocked
Query HistoricalInfo
I[2020-10-21|18:04:12.240] - [stargate-4]@{95490}chan(sleepsrcchan)-{STATE_INIT} : [slippy-0]@{104058}chan(sleepdstchan)-{STATE_TRYOPEN} 
I[2020-10-21|18:04:12.716] - [stargate-4] -> sending transaction:       
E[2020-10-21|18:04:12.716] - [stargate-4] -> err(failed to execute message; message index: 1: channel handshake open ack failed: channel state should be INIT or TRYOPEN (got STATE_OPEN): invalid channel state: invalid request) 
I[2020-10-21|18:04:12.716] retrying transaction...                      
try unlock
unlocked
try unlock
Query HistoricalInfo
unlocked
Query HistoricalInfo
I[2020-10-21|18:04:18.479] - [slippy-0]@{104060}chan(sleepdstchan)-{STATE_TRYOPEN} : [stargate-4]@{95491}chan(sleepsrcchan)-{STATE_OPEN} 
I[2020-10-21|18:04:23.006] ✔ [slippy-0]@{104061} - msg(0:update_client,1:channel_open_confirm) hash(CE216C159513A261BB358A400050D47597E19D99904408B2B0D103D19AAB915C) 
I[2020-10-21|18:04:23.274] - [stargate-4]@{0}chan(sleepsrcchan)-{STATE_UNINITIALIZED_UNSPECIFIED} : [slippy-0]@{0}chan(sleepdstchan)-{STATE_UNINITIALIZED_UNSPECIFIED} 
I[2020-10-21|18:04:23.274] ★ Channel created: [stargate-4]chan{sleepsrcchan}port{transfer} -> [slippy-0]chan{sleepdstchan}port{transfer} 
```

Full handshake works with single command!! Ignore debugging prints

**Comment by AdityaSripal** [comment]
Tested and it works, reviewers please verify this works locally

**Comment by AdityaSripal** [comment]
Called `defer unlock` after most calls to SetLock which prevents accidentally not unlocking and returning early.

The only places where I don't is if there are multiple `SetLock` calls in the same function AND there is no possibility of returning early before the unlock call

**Review by cwgoes — APPROVED** [review]
tACK, works locally at least

We should abstract this concurrency code better, perhaps?

**Review by zmanian — APPROVED** [review]

**Pull request merged**
