### PR TITLE
add everstakechain.json

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by everstake** [comment]
Add everstakechain to testnet

**Comment by jackzampolin** [comment]
I'm failing to create a connection with your chain. The error is in the connection open try step:

```
I[2020-04-26|00:35:21.494] - [everstakechain]@{0}conn(gdsasryuwo)-{UNINITIALIZED} : [pylonchain]@{23514}conn(fwjggdpheb)-{INIT} 
I[2020-04-26|00:35:22.767] - [everstakechain] -> sending transaction:   
[{"type":"ibc/client/tendermint/MsgUpdateClient","value":{"client_id":"itiaowtinm","header":{"SignedHeader":{"header":{"version":{"block":"10","app":"0"},"chain_id":"pylonchain","height":"23515","time":"2020-04-26T00:35:14.607501041Z","last_block_id":{"hash":"EB6C39653C5D7C81683ECA480CC84591007532A8C4BED14A87F2F84CF05235C3","parts":{"total":"1","hash":"04EDB6B55A0BE674ACB5F960AAA5D187E4A1BB93B1ED3A600F277531FA1741AD"}},"last_commit_hash":"56369FB0D7EAF51B303529F73368290C2E30EFC370DA5CDDBEECB9DC567FD0F8","data_hash":"","validators_hash":"9015AAC0DAF1191E8520F4CAF3CF556ADB0031571444129FF3A46DAC05C9A35C","next_validators_hash":"9015AAC0DAF1191E8520F4CAF3CF556ADB0031571444129FF3A46DAC05C9A35C","consensus_hash":"048091BC7DDC283F77BFBF91D73C44DA58C3DF8A9CBC867405D8B7F3DAADA22F","app_hash":"AA23241861227F471426EDDE35CF839AF1414ED9E070060AD0F6F57F31F48533","last_results_hash":"","evidence_hash":"","proposer_address":"ED91ED9F55D2ED8855F9F6F0492407ED23D151F9"},"commit":{"height":"23515","round":"0","block_id":{"hash":"A1A73788429208B5B890C3DFAC44D008B90DF4BA9C309C9060E8DB9650A13004","parts":{"total":"1","hash":"5B471A3851FD0C035848D495635EE5022647A9873A4971882B84D47CC3D56D83"}},"signatures":[{"block_id_flag":2,"validator_address":"ED91ED9F55D2ED8855F9F6F0492407ED23D151F9","timestamp":"2020-04-26T00:35:19.627160947Z","signature":"V2LOhNvJ5PyXupgrZFjdGhCMmEz6gMVTA49x5Nw3GHyPk2vweUDQ7g4Czp1X3fx4wQmMt+ZzGRyttw4tW4oeBw=="}]}},"validator_set":{"validators":[{"address":"ED91ED9F55D2ED8855F9F6F0492407ED23D151F9","pub_key":{"type":"tendermint/PubKeyEd25519","value":"MKw4z3WwrTY6aFJBnbozUJhy1JpogyXurJv1glnCmqc="},"voting_power":"90000","proposer_priority":"0"}],"proposer":{"address":"ED91ED9F55D2ED8855F9F6F0492407ED23D151F9","pub_key":{"type":"tendermint/PubKeyEd25519","value":"MKw4z3WwrTY6aFJBnbozUJhy1JpogyXurJv1glnCmqc="},"voting_power":"90000","proposer_priority":"0"}}},"address":"cosmos13xjrp283vqs352s2ley88cmtj6ngrkzqhjsrhe"}},{"type":"ibc/connection/MsgConnectionOpenTry","value":{"connection_id":"gdsasryuwo","client_id":"itiaowtinm","counterparty":{"client_id":"dksvfbwxxl","connection_id":"fwjggdpheb","prefix":{"type":"ibc/commitment/MerklePrefix","value":{"key_prefix":"aWJj"}}},"counterparty_versions":["1.0.0"],"proof_init":{"type":"ibc/commitment/MerkleProof","value":{"proof":{"ops":[{"type":"iavl:v","key":"Y29ubmVjdGlvbnMvZndqZ2dkcGhlYg==","data":"0QMKzgMKKwgUEI8DGNS3ASIgbodA/i67Nf+elpvwkVtu4oTpu+S+Gj5Jsw1cOUpoB24KKwgSEMwBGNS3ASIgh9rkWMApk12e3SPcmDdOK/EqwcpTsL8Ha807cQZuK0MKKggQEFcY1LcBKiBcmLXs8LCOjGUfKMkkS64ciCOnHjIrXo+nMcwhRQIhDQoqCAwQIRjUtwEiIHQtKJ9xfu+XPj6p2VWQvPmJupi4XZtJJxrkm7a+2JObCioIChAUGNS3ASIgCaXpMxSPvXN91tgsnwb80Vtdeu9q/Ldq8e+0q3TbNlEKKggIEAsY1LcBKiCnA94a0gQemTa59q1exnlXzNfHLSWfdnb4oihLXep3SgoqCAYQBxjUtwEqILONFv7URVsV1DEvJWacnYI98M0Jsw28jysh9C5kFDbCCioIBBAEGNS3ASIgTsdSm31lBpLjdUzt3lJdqy8loWMsH6KCmgolHKaCe04KKggCEAIY1LcBIiCbIxaLSTHJZ+o0kI1dlfZ44d/Nu3l02V3MdB8kZZKjAxo+ChZjb25uZWN0aW9ucy9md2pnZ2RwaGViEiDg+lYW7F+5zI5CQJvkeXJa7oWpgDl+tIcyX1rWZHYxExjUtwE="},{"type":"multistore","key":"aWJj","data":"CvcECjAKBGJhbmsSKAomCNq3ARIgvZKXkyAMPr6+Ks91Iw6G+PGMQSt1auIDv3GSYSK9OY4KEAoObWVtX2NhcGFiaWxpdHkKEQoHdXBncmFkZRIGCgQI2rcBCjgKDGRpc3RyaWJ1dGlvbhIoCiYI2rcBEiBoGHH8YIDTgxkHjc4bJNlhBWQMQOer7I7QS69sf1H5vwo0Cgh0cmFuc2ZlchIoCiYI2rcBEiCtdxLMpRJ0Aom3FLEbmPPES9H/JukxNJ0t6SoQH+KRBwowCgRtaW50EigKJgjatwESIMmO2mx1m5ICey5Y6OqxesakoPQEIKFxBWLy44/vHFefCi8KA2liYxIoCiYI2rcBEiBsJ0Zlk/WCsCTWNp8ny3LIVO9lyeB89Ks51xB61942NAoSCghldmlkZW5jZRIGCgQI2rcBCi8KA2FjYxIoCiYI2rcBEiDJSe6dfGdaRvItcOmHSezUSNitMn/140PFboRydOb2CgovCgNnb3YSKAomCNq3ARIgYM0TfBli7KxhY4nWgDSDPykhUJwtKFql9RU5l86WinQKMgoGcGFyYW1zEigKJgjatwESIGkj67y18GFkEkKFw9okZW6obf4bsPrjr5ja/dB8aaq/CjQKCHNsYXNoaW5nEigKJgjatwESIMK4x0JYxtB3BaY94YMQf8a1DRXvUNp2VbfdRA68ICSICjMKB3N0YWtpbmcSKAomCNq3ARIgD2sU51AWJzRAaEnXhsfMHSTFDnh9pb1Ra3NR8GIDHnwKNgoKY2FwYWJpbGl0eRIoCiYI2rcBEiBj1Lmi4cxkrv0oOrOrfiM16qbWvsGoJwvDcwkksCpVqA=="}]}}},"proof_consensus":{"type":"ibc/commitment/MerkleProof","value":{"proof":{"ops":[{"type":"iavl:v","key":"Y2xpZW50cy9ka3N2ZmJ3eHhsL2NvbnNlbnN1c1N0YXRlLzE3NDcz","data":"4gMK3wMKKwgUEI8DGNS3ASogCkGcySA9CdNJRLAg0UgJGZZaG20oievPdY5lcO3A/kQKKwgSEMMBGNS3ASogSahdXSGzi0lLMzQl87rCJLZk1758kmKuCAcwclm3QbsKKggQEE0Y1LcBIiDx25AJXB983miHJoKRWuZt0LdDfnIooDtZdK54nShHOAoqCA4QLxjUtwEiIASbHnUI42qSfNXYy1MbBoEthJsl+HIbFiRBzm/u5BuSCioIChARGNS3ASIg3tfm6qGgqP2bGSnQIsoks/ka+2+8JnhyIukQrIJ8VqUKKggIEAsY7JYBKiDXqQEilq2S0DfyvBaKyymlT8+T6JAVICb0wn4uA7ak4woqCAYQCBjslgEiIJlmqe2q2h1TR+LntrsAESvl+esFf8u+zXC4pXyzku8MCioIBBAEGOyWASIgC3ilOd7KA7wReKP1WwxV+ulDXwCoMfZ2EjeggMJuoXwKKggCEAIY7JYBIiCLTeDywnHD/INZBKK+Ii+ifSbcrDp4q3ElZd2NC0ZeIBpPCidjbGllbnRzL2Rrc3ZmYnd4eGwvY29uc2Vuc3VzU3RhdGUvMTc0NzMSILN8H+Ek6tQHYEYwf7qCj+T87kzlykiJNZ82sqJtrYCUGOyWAQ=="},{"type":"multistore","key":"aWJj","data":"CvcECjAKBGJhbmsSKAomCNq3ARIgvZKXkyAMPr6+Ks91Iw6G+PGMQSt1auIDv3GSYSK9OY4KEAoObWVtX2NhcGFiaWxpdHkKEQoHdXBncmFkZRIGCgQI2rcBCjgKDGRpc3RyaWJ1dGlvbhIoCiYI2rcBEiBoGHH8YIDTgxkHjc4bJNlhBWQMQOer7I7QS69sf1H5vwo0Cgh0cmFuc2ZlchIoCiYI2rcBEiCtdxLMpRJ0Aom3FLEbmPPES9H/JukxNJ0t6SoQH+KRBwowCgRtaW50EigKJgjatwESIMmO2mx1m5ICey5Y6OqxesakoPQEIKFxBWLy44/vHFefCi8KA2liYxIoCiYI2rcBEiBsJ0Zlk/WCsCTWNp8ny3LIVO9lyeB89Ks51xB61942NAoSCghldmlkZW5jZRIGCgQI2rcBCi8KA2FjYxIoCiYI2rcBEiDJSe6dfGdaRvItcOmHSezUSNitMn/140PFboRydOb2CgovCgNnb3YSKAomCNq3ARIgYM0TfBli7KxhY4nWgDSDPykhUJwtKFql9RU5l86WinQKMgoGcGFyYW1zEigKJgjatwESIGkj67y18GFkEkKFw9okZW6obf4bsPrjr5ja/dB8aaq/CjQKCHNsYXNoaW5nEigKJgjatwESIMK4x0JYxtB3BaY94YMQf8a1DRXvUNp2VbfdRA68ICSICjMKB3N0YWtpbmcSKAomCNq3ARIgD2sU51AWJzRAaEnXhsfMHSTFDnh9pb1Ra3NR8GIDHnwKNgoKY2FwYWJpbGl0eRIoCiYI2rcBEiBj1Lmi4cxkrv0oOrOrfiM16qbWvsGoJwvDcwkksCpVqA=="}]}}},"proof_height":"23515","consensus_height":"17473","signer":"cosmos13xjrp283vqs352s2ley88cmtj6ngrkzqhjsrhe"}}]
I[2020-04-26|00:35:22.768] ✘ [everstakechain]@{2520} - msg(0:update_client,1:connection_open_try) err(ibc: invalid height) 
{"height":"2520","txhash":"912EDD3FE8851F3B4C7EF5920BABF30809ED06DB29CB30A3DD6169461A979EE1","codespace":"ibc","code":1,"raw_log":"internal error","gas_wanted":"200000","gas_used":"109066"}
```

**Comment by everstake** [comment]
I delete gaiad and folders. I delete repositories and start setup all again. Please check it now.
My connection worked
rly tx link everpyl
I[2020-04-26|07:34:16.044] ✔ [everstakechain]@{168} - msg(0:create_client) hash(6B7C2153A4BCF9DD6E80680B549B185A97C0B51E7F9289D5E414E2A47F830B8F)
I[2020-04-26|07:34:20.002] ✔ [pylonchain]@{28522} - msg(0:create_client) hash(1F0B09091C36D8D1F1E24F6DCE52B7CC7DC961584E22DC5C8CD2E337E1E9AD8A)
I[2020-04-26|07:34:20.002] ★ Clients created: [everstakechain]client(kbdtrtmafa) and [pylonchain]client(dkstrbwxxl)
I[2020-04-26|07:34:21.082] ✔ [everstakechain]@{169} - msg(0:connection_open_init) hash(CE804FE8256D5984B607ADC2635925C26811A5FAB9C65ABDF5D37D5448B063F0)
I[2020-04-26|07:34:35.064] ✔ [pylonchain]@{28525} - msg(0:update_client,1:connection_open_try) hash(58503B133A79120228129C9189906A6648BC503447375EE1121C2EDA5598C392)
I[2020-04-26|07:34:41.249] ✔ [everstakechain]@{173} - msg(0:update_client,1:connection_open_ack) hash(FFA28946A9F8F9ED74FDD53E949E2214D9737881F887F6C030FC8236535696D4)
I[2020-04-26|07:34:55.141] ✔ [pylonchain]@{28529} - msg(0:update_client,1:connection_open_confirm) hash(6D860BDA910B8309146082B0B94B78205F3D2E7352C19699B6C0E12A12225858)
I[2020-04-26|07:34:55.141] ★ Connection created: [everstakechain]client{kbdtrtmafa}conn{jqgfarcdmz} -> [pylonchain]client{dkstrbwxxl}conn{gjnngjrqvo}
I[2020-04-26|07:34:56.381] ✔ [everstakechain]@{176} - msg(0:channel_open_init) hash(DD15C46CA828141CB2C5A8B9A74E7E36D92D18790E8FA7899F1A357C30760BDA)
I[2020-04-26|07:35:10.216] ✔ [pylonchain]@{28532} - msg(0:update_client,1:channel_open_try) hash(4BABF2C2D2DCBBE0183E0798D10B18C0A0A1EA46A043F4E7CFDC8AD52BDF4228)
I[2020-04-26|07:35:16.576] ✔ [everstakechain]@{180} - msg(0:update_client,1:channel_open_ack) hash(95BEE76F34C2BB89304626CEEDA2031B0F8789B63BE95B83E26E93FEED1A2227)
I[2020-04-26|07:35:30.294] ✔ [pylonchain]@{28536} - msg(0:update_client,1:channel_open_confirm) hash(6607AB041620F52DF64BB5F14DB47B75DF6A5742D7D70633520EE03D57136C3A)
I[2020-04-26|07:35:30.426] ★ Channel created: [everstakechain]chan{nfhgcuvxza}port{transfer} -> [pylonchain]chan{gethqdursi}port{transfer}

**Comment by jackzampolin** [comment]
This is great! Merging now as I see the working connection on my end and I'm able to relay across it!

**Pull request merged**
