### PR TITLE
Clean up scripts folder

### LINKED ISSUE #872: The `scripts/` folder should be cleaned up and organzied
Many of the these bash scripts are duplicates and/or can be replaced by `ibctest`

### PR DESCRIPTION
**Pull request by boojamya**
This PR cleans up the extra scrips in the scripts folder along with any config files associated with them.
If these test environments are needed in the future, they should be created with `ibc-test`

The `dev-env` script is a great learning experience for new comers and I think we should keep it around. Since `dev-env` leverages both `two-chainz` and `one-chain` these have not been removed.

This also cleans up the Makerfile.

Closes: https://github.com/cosmos/relayer/issues/872

### CODE REVIEW

**Comment by boojamya** [comment]
Any thoughts on moving `dev-env`, `scripts` folder, and `configs` folder into one top level folder called "demo"?

...and adjusting scripts as necessary?

**Comment by boojamya** [comment]
Changing to draft. Going to re-organize as noted above ^

**Comment by boojamya** [comment]
UPDATE:
This is mainly a clean up PR.

- Moves all `dev-env` related files and folder to an `examples` folder.
- Add readme to examples folder explaining dev-env scripts.
- Adds fully built out config example
- Updates relevant Makerfile paths
- Updates description pointing to old path in `rly paths add-dir` command
- Removes extra scripts for test-net environments (as noted in initial comment)

**Review by jtieri — APPROVED** [review]
This looks great Dan, great cleanup here!!
I didn't clone down the updated files and run the demo but I trust that you have been running them while you edit to ensure nothing is bricked.

**Pull request merged**
