### PR TITLE
Fix integration tests

### PR DESCRIPTION
**Pull request by colin-axner**
working on uploading a docker image for gaia 3.0

### CODE REVIEW

**Comment by colin-axner** [comment]
unsure what I'm doing wrong, 

go to gaia
run `make test-docker-push`, use tags in `/test/test_chains.go` in relayer
but I get
```
could not connect to container at http://localhost:33853: post failed: Post "http://localhost:33853": dial tcp [::1]:33853: connect: connection refused

```

**Comment by colin-axner** [comment]
docker needs to be debugged `docker logs [container-id]`. If anyone can help with this, that would be much appreciated :pray:

**Comment by ethanfrey** [comment]
I get the following from `docker log...` when doing `make test-gaia` on your branch.
This is related to the following issue: https://github.com/cosmos/relayer/issues/353

```
$ docker logs 2be410bd429c
{"app_message":{"auth":{"accounts":[],"params":{"max_memo_characters":"256","sig_verify_cost_ed25519":"590","sig_verify_cost_secp256k1":"1000","tx_sig_limit":"7","tx_size_cost_per_byte":"10"}},"bank":{"balances":[],"denom_metadata":[],"params":{"default_send_enabled":true,"send_enabled":[]},"supply":[]},"capability":{"index":"1","owners":[]},"crisis":{"constant_fee":{"amount":"1000","denom":"stake"}},"distribution":{"delegator_starting_infos":[],"delegator_withdraw_infos":[],"fee_pool":{"community_pool":[]},"outstanding_rewards":[],"params":{"base_proposer_reward":"0.010000000000000000","bonus_proposer_reward":"0.040000000000000000","community_tax":"0.020000000000000000","withdraw_addr_enabled":true},"previous_proposer":"","validator_accumulated_commissions":[],"validator_current_rewards":[],"validator_historical_rewards":[],"validator_slash_events":[]},"evidence":{"evidence":[]},"genutil":{"gen_txs":[]},"gov":{"deposit_params":{"max_deposit_period":"172800s","min_deposit":[{"amount":"10000000","denom":"stake"}]},"deposits":[],"proposals":[],"starting_proposal_id":"1","tally_params":{"quorum":"0.334000000000000000","threshold":"0.500000000000000000","veto_threshold":"0.334000000000000000"},"votes":[],"voting_params":{"voting_period":"172800s"}},"ibc":{"channel_genesis":{"ack_sequences":[],"acknowledgements":[],"channels":[],"commitments":[],"next_channel_sequence":"0","receipts":[],"recv_sequences":[],"send_sequences":[]},"client_genesis":{"clients":[],"clients_consensus":[],"clients_metadata":[],"create_localhost":false,"next_client_sequence":"0","params":{"allowed_clients":["06-solomachine","07-tendermint"]}},"connection_genesis":{"client_connection_paths":[],"connections":[],"next_connection_sequence":"0"}},"mint":{"minter":{"annual_provisions":"0.000000000000000000","inflation":"0.130000000000000000"},"params":{"blocks_per_year":"6311520","goal_bonded":"0.670000000000000000","inflation_max":"0.200000000000000000","inflation_min":"0.070000000000000000","inflation_rate_change":"0.130000000000000000","mint_denom":"stake"}},"params":null,"slashing":{"missed_blocks":[],"params":{"downtime_jail_duration":"600s","min_signed_per_window":"0.500000000000000000","signed_blocks_window":"100","slash_fraction_double_sign":"0.050000000000000000","slash_fraction_downtime":"0.010000000000000000"},"signing_infos":[]},"staking":{"delegations":[],"exported":false,"last_total_power":"0","last_validator_powers":[],"params":{"bond_denom":"stake","historical_entries":10000,"max_entries":7,"max_validators":100,"unbonding_time":"1814400s"},"redelegations":[],"unbonding_delegations":[],"validators":[]},"transfer":{"denom_traces":[],"params":{"receive_enabled":true,"send_enabled":true},"port_id":"transfer"},"upgrade":{},"vesting":{}},"chain_id":"ibc-1","gentxs_dir":"","moniker":"ibc-1","node_id":"455dc2dd300a0906bd553afff4cc705dd0405436"}


**Important** write this mnemonic phrase in a safe place.
It is the only way to recover your account if you ever forget your password.

meat popular cricket solid review improve glass neglect label curve range trophy column mistake senior donor thing dragon six shiver desk health style curtain
- name: validator
  type: local
  address: cosmos1f8ya95vf5g68jwdxagt07ey6mrvdpmlrucnp2t
  pubkey: cosmospub1addwnpepq056n3rvrc36tn89p3fw5axtsed73yhcrdvte3akt03d9dgzzacx29652a9
  mnemonic: ""
  threshold: 0
  pubkeys: []

Error: accepts 2 arg(s), received 1
Usage:
  gaiad gentx [key_name] [amount] [flags]

...
```

**Comment by ethanfrey** [comment]
I am finding this extremely hard to debug/reproduce as the actual startup scripts are not in cosmos/gaia:main nor in this repo as far as I can tell, but in some opaque docker image.

I would highly suggest using a default `gaia:v3.0.0` image for the tests and do the setup as a script (in this repo) that can initialize that docker image. That would make a quick feedback loop to adjust the startup scripts.

**Comment by ethanfrey** [comment]
@colin-axner There is a fix to the docker file here: https://github.com/cosmos/gaia/pull/537 I will test it now

**Comment by colin-axner** [comment]
thanks for the assistance @ethanfrey !! 

> I would highly suggest using a default gaia:v3.0.0 image for the tests and do the setup as a script (in this repo) that can initialize that docker image.

I completely agree. Trying to fix these integration test by uploading a new docker image has been very confusing and isn't sustainable or easily maintainable. I'm new to Docker, but it sounds like we should copy over the `Dockerfile.test` in gaia, modify where it copies the source files from and then also copy over the setup script. If possible automating the upload on the github CI would be great

**Comment by ethanfrey** [comment]
Fixed in #359 

Let's try and merge that.
That also makes use of https://github.com/cosmos/gaia/pull/537 to address #353 

For #353 we need to make similar updates to the scripts in this repo. And I also think moving the test Dockerfile in this repo make sense. But let's do those in another PR. (The test dockerfile would be easy if there were a standard gaia image we could extend - eg. `FROM cosmos/gaia:v3.0.0`...

**Comment by colin-axner** [comment]
fixed by #359

**Pull request closed without merging**
