### PR TITLE
Use updated version of lens

### LINKED ISSUE #746: ibc relayer betweet Evmos and Evmos error
I use two evmos chains to test ibc  

Run command  `rly  tx link path -d`
error : `no concrete type registered for type URL /ethermint.types.v1.EthAccount against interface *types.AccountI`

Evmos version 4.0.0   ethermint  version 0.15.0

### LINKED ISSUE #748: Evmos public keys do not yield the same public key that keplr displays when restoring key
If you restore a key for evmos using your seed you don't get the same public key that is displayed in Keplr, I tried with both coin type 118 and 60.

### PR DESCRIPTION
**Pull request by jtieri**
Thanks to @joeabbey & @giansalex we have support for Ethereum based accounts in [lens](https://github.com/strangelove-ventures/lens/pull/168) so updating to the latest release of lens should rectify the issues around Evmos that users have experienced in the relayer.

Closes #748 
Closes #746

### CODE REVIEW

**Review by mark-rushakoff — COMMENTED** [review]
```
#18 122.1 cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
```

Looks like the dockerfile will need to learn about gcc. I don't remember offhand if just `gcc` suffices in alpine or if there's more to it.

**Comment by jtieri** [comment]
> ```
> #18 122.1 cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
> ```
> 
> Looks like the dockerfile will need to learn about gcc. I don't remember offhand if just `gcc` suffices in alpine or if there's more to it.

Okay looks like both Dockerfiles needed the full gcc tools suite; it should be good to go now.

**Review by mark-rushakoff — APPROVED** [review]
Would be interesting to understand what specifically caused the gcc dependency.

**Comment by jtieri** [comment]
> Would be interesting to understand what specifically caused the gcc dependency.

Was digging into this a bit and I believe it was the introduction of `github.com/tharsis/ethermint` in `lens` for supporting Ethereum based accounts.

**Pull request merged**
