### PR TITLE
Continued account prefix fixes 

### PR DESCRIPTION
**Pull request by jackzampolin**
ref: https://github.com/iqlusioninc/relayer/issues/43

### CODE REVIEW

**Comment by jackzampolin** [comment]
This is working for me! Looks like we have this issue fixed for the moment.

**Comment by zmanian** [comment]
This whole thing is just a race condition waiting to happen.

We need to find a way that doesn't relay on global state.

**Comment by zmanian** [comment]
More specifically, inside at the function call boundary, if running inside a goroutine, the go scheduler can context switch. 

There may be a way to prevent this using something that prevents the go scheduler from context switching until the function returns.

go routine safety doesn't generally matter in the SDK because it's largely single threaded. But it will probably end up mattering the in the relayer.

**Comment by jackzampolin** [comment]
@zmanian the global we are relying on is in the SDK. We would need to fix this issue there.

**Pull request merged**
