### PR TITLE
use the name given by the user to generate the fetch URL

### PR DESCRIPTION
**Pull request by murataniloener**
`GetChain` and `GetChainConfig` generate the URLs in different ways, but the [chain registry](https://github.com/cosmos/chain-registry) has `chain.json` and `assetlist.json` always in the same directory. So I am passing the `name`  in `GetChainConfig` in order to mimic the `GetChain`, but I can imagine a better way that uses a common base URL for both functions.

### CODE REVIEW

**Comment by murataniloener** [comment]
Just a heads up, the reason for the fix is that atm fetching testnet configs via `rly chains add testnets/testnet_name` does not work. The command cannot fetch `assetlist.json` from the URL generated with `c.ChainName`.

**Comment by murataniloener** [comment]
Closes #1128

**Review by agouin — APPROVED** [review]
Thank you!

**Comment by boojamya** [comment]
Nice fix! @murataniloener 
Adding to the cmd examples and/or adding to the `short` description in `cmd/chains.go` could go a long way here for users to know this is possible.

**Comment by murataniloener** [comment]
Is [this](https://github.com/cosmos/relayer/pull/1233/commits/3b2be42d94c097005b40550ce69187068e6f93c4) enough or do you have something else in mind?

**Review by boojamya — APPROVED** [review]

**Pull request merged**
