### PR TITLE
ADD chain

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jackzampolin** [comment]
I'm getting this error when trying to connect with your chain:

```
$ rly lite i stakematic-asia -f
Error: no witnesses connected. please reset light client
no witnesses connected. please reset light client
```

Do you mind sharing with me the `go.mod` files from both the relayer and the SDK app you are using? I've heard about this error but have been unable to reproduce it until now.

**Comment by stakematic** [comment]
## relayer

~/go/src/github.com/iqlusioninc/relayer$ cat go.mod
module github.com/iqlusioninc/relayer

go 1.14

require (
	github.com/avast/retry-go v2.6.0+incompatible
	github.com/cenkalti/backoff/v3 v3.2.2 // indirect
	github.com/containerd/continuity v0.0.0-20200228182428-0f16d7a0959c // indirect
	github.com/cosmos/cosmos-sdk v0.34.4-0.20200423152229-f1fdde5d1b18
	github.com/cosmos/go-bip39 v0.0.0-20180819234021-555e2067c45d
	github.com/gorilla/mux v1.7.4
	github.com/ory/dockertest/v3 v3.5.5
	github.com/sirkon/goproxy v1.4.8
	github.com/sirupsen/logrus v1.5.0 // indirect
	github.com/spf13/cobra v1.0.0
	github.com/spf13/viper v1.6.3
	github.com/stretchr/testify v1.5.1
	github.com/tendermint/go-amino v0.15.1
	github.com/tendermint/tendermint v0.33.4
	github.com/tendermint/tm-db v0.5.1
	gopkg.in/yaml.v2 v2.2.8
)

replace github.com/keybase/go-keychain => github.com/99designs/go-keychain v0.0.0-20191008050251-8e49817e8af4

## gaia  



cat go.mod
module github.com/cosmos/gaia
go 1.14

require (
	github.com/cosmos/cosmos-sdk v0.34.4-0.20200423152229-f1fdde5d1b18
	github.com/onsi/ginkgo v1.8.0 // indirect
	github.com/onsi/gomega v1.5.0 // indirect
	github.com/otiai10/copy v1.1.1
	github.com/pkg/errors v0.9.1
	github.com/snikch/goodman v0.0.0-20171125024755-10e37e294daa
	github.com/spf13/cobra v1.0.0
	github.com/spf13/viper v1.6.3
	github.com/stretchr/testify v1.5.1
	github.com/tendermint/go-amino v0.15.1
	github.com/tendermint/tendermint v0.33.4
	github.com/tendermint/tm-db v0.5.1
)

**Comment by daluxxx** [comment]
Its the same error that I had. Its because there is the word "stake" in his Chain ID. 
After the command "sed -i "s/stake/$DENOM/g" ~/.gaiad/config/genesis.json" the Chain ID in the genesis.json is not correct anymore. Same issue as #124 .

**Comment by stakematic** [comment]
@daluxxx Wonderful, you are correct, it is because the "stake" is part of our chain ID.

@jackzampolin I find and replace "stake" with double quotes altogether.  It works fine.
sed -i "s/\"stake\"/\"$DENOM\"/g" ~/.gaiad/config/genesis.json

**Review by jackzampolin — APPROVED** [review]
Thank you for the sed fix @stakematic !!

**Pull request merged**
