### PR TITLE
security: fix leaks identified from staticmajor + add config

### PR DESCRIPTION
**Pull request by odeke-em**
This change fixes resource leaks identified by a static analyzer from Orijtech Inc called "staticmajor".

While here, also added the Github config so that this change is ran on every push to main or a PR.

### CODE REVIEW

**Review by agouin — APPROVED** [review]
Thank you for this!

**Comment by agouin** [comment]
@odeke-em please update this branch with our latest main changes and we will get it merged in!

**Comment by odeke-em** [comment]
Done, I've made the rebase from main; thanks for the review @agouin!

**Comment by jtieri** [comment]
Closed by #1114

**Pull request closed without merging**
