### PR TITLE
Add blockngine-ibc

### PR DESCRIPTION
**Pull request by AutoStake1**

### CODE REVIEW

**Comment by jackzampolin** [comment]
I'm unable to request funds from your faucet:
```
$ rly tst req blockngine-ibc
{"error":"codespace for (0) not found in map"}
```
please make sure that both the relayer and gaia are at the versions suggested here: https://github.com/iqlusioninc/relayer/tree/master/testnets

**Comment by AutoStake1** [comment]
Yeah I am experiencing the same problem

Gaiad is version 0.0.0-180-g50be36d
Relayer is:
version: 0.3.0
commit: 781026cf46c6d144ab7fcd02d92817cc3d524903
cosmos-sdk: v0.34.4-0.20200423152229-f1fdde5d1b18
go: go1.13.6 linux/amd64

Both are running in the same docker container and I still get the issue, I've seen you suggest in telegram before that it could be local issue with chain, so I'm trying to look into that currently, see if I can find anything

**Comment by AutoStake1** [comment]
This is now working @jackzampolin 

The problem was I had to use the same key that was in gentx / genesis file

**Comment by jackzampolin** [comment]
Closing in favor of the https://github.com/cosmosdevs/GameOfZones repo.

**Pull request closed without merging**
