### PR TITLE
feat: allow building a shared library

### PR DESCRIPTION
**Pull request by michaelfig**
These are the changes needed to support the Agoric smart-relay.

Documentation will be included before merging.

### CODE REVIEW

**Comment by jackzampolin** [comment]
Does this PR introduce a cgo dep?

**Comment by michaelfig** [comment]
> Does this PR introduce a cgo dep?

Only if you explicitly build the library.  Otherwise, there is no C FFI in the existing relayer binary.

**Comment by jackzampolin** [comment]
This PR would need to be updated to work with the latest code. Just a quick glance implies that not much has changed.

**Comment by michaelfig** [comment]
> This PR would need to be updated to work with the latest code. Just a quick glance implies that not much has changed.

I'll do that update once my inbox is more empty. 😃

**Comment by michaelfig** [comment]
> This PR would need to be updated to work with the latest code. Just a quick glance implies that not much has changed.

R4R!  I don't see it passing CI, but then again it appears that most of master doesn't pass CI.

**Pull request merged**
