### PR TITLE
Pull chain data from Chain Registry, Add paths new cmd, & Improve CLI experience/quick-start guide

### LINKED ISSUE #538: Refactor fetching chain configuration to use chain-registry
The relayer currently has `fetch` commands that are used to pull canonical metadata, regarding chains/paths, from the GitHub repo [here](https://github.com/cosmos/relayer/tree/main/interchain)

To reduce redundancy we want to import this data from the [chain-registry](https://github.com/cosmos/chain-registry)

[lens](https://github.com/strangelove-ventures/lens/tree/main/internal/chain_registry) has this functionality built in and is already a dep for the relayer so ideally we use lens to pull this data from chain-registry

### PR DESCRIPTION
**Pull request by jtieri**
[lens](https://github.com/strangelove-ventures/lens) now contains the facilities for fetching chain metadata from the [chain-registry](https://github.com/cosmos/chain-registry). 

This PR removes the `fetch` cmd tree from the relayer in favor of using lens for fetching this chain metadata. Users can now specify which chains they want to pull data for in `rly chains add [chain names]` 
e.g. `rly chains add osmosis cosmoshub`

Because the chain-registry does not contain the necessary metadata for paths we still need to maintain this data ourselves but instead of using the `fetch` cmd tree users can use `rly paths fetch` which will pull the paths for every chain they have configured via `rly chains add`

#564 adds a new command `rly paths new [src-chain-id] [dst-chain-id] [path-name] [flags]` which will generate a new blank path between src and dst in your `config.yaml` file 

Closes #538

### CODE REVIEW

**Comment by boojamya** [comment]
Want to note that I experienced this issue (https://github.com/cosmos/relayer/issues/562) when adding chains today.

**Comment by jtieri** [comment]
> Want to note that I experienced this issue (#562) when adding chains today.

Interesting, maybe we can increase the rate limit enough to not hit these errors using authenticated requests.

```
Error: GET https://api.github.com/repos/cosmos/chain-registry/git/trees/master: 403 API rate limit exceeded for 172.xxx.xxx.xx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.
```
https://github.com/google/go-github#authentication

Maybe this is a per user basis though? Managing tokens as a user seems like bad UX so perhaps we do want to clone the repo and traverse the files locally to move from making multiple calls to the GitHub API to only one every time `rly chains add` is called

**Comment by boojamya** [comment]
Read through some of the docs. It's confusing b/c its different on how you set it up and github user status. I can't imagine I hit the rate limit as and individual user. Without an enterprise account I get 5000 requests per hour. ¯\_(ツ)_/¯

So... check this out:

> When using the built-in GITHUB_TOKEN in GitHub Actions, the rate limit is 1,000 requests per hour per repository. For organizations that belong to a GitHub Enterprise Cloud account, this limit is 15,000 requests per hour per repository.
> 
> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

(From: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting)

So I guess it depends on how we implemented the API call... and it could be repo based.

I do think pulling the whole chain registry repo down is a good quick fix though. OR pointing to URL specifically.

**Review by boojamya — APPROVED** [review]
love these features.

**Pull request merged**
