### PR TITLE
Refactor relayUnrelayedPacketsAndAcks

### PR DESCRIPTION
**Pull request by mark-rushakoff**
Reorganize relayUnrelayedPacketsAndAcks so that context cancellation
should take immediate effect, without blocking on a sleep.

Change the signature on both relayUnrelayedPackets and
relayUnrelayedAcks to return a bool and internally log errors, rather
than returning an error that was only used for control flow. Now, the
error logging makes more sense in the local scope.

Reorganize both of those functions to return early if there is nothing
to relay.

Stop using explicit context cancellation for control flow. Instead, rely
on RelayPackets or RelayAcknowledgements to return the context error
upon cancellation or deadline exceeded, and treat that case separately
from an application-level error. This also means those functions don't
need to run in their own goroutine.

### CODE REVIEW

**Comment by jtieri** [comment]
Everything looks good; much cleaner and easier to follow what's going on.

Ran this against Sommelier<->Osmosis mainnets just to be sure everything is working as intended in a production setting and I noticed that the logging for context timeouts/cancelations doesn't seem to get logged.

https://github.com/cosmos/relayer/blob/refactor/relay-unrelayed/relayer/strategies.go#L321-L334

I can tell the context does timeout in some cases by the logs. In the below logs we can see that the `45s` deadline for the context passes but the log is absent.
```
2022-03-31T21:54:04.107272Z     info    No acknowledgements in queue    {"src_chain_id": "sommelier-3", "src_channel_id": "channel-0", "src_port_id": "transfer", "dst_chain_id": "osmosis-1", "dst_channel_id": "channel-165", "dst_port_id": "transfer"}
2022-03-31T21:54:51.538910Z     info    No acknowledgements in queue    {"src_chain_id": "sommelier-3", "src_channel_id": "channel-0", "src_port_id": "transfer", "dst_chain_id": "osmosis-1", "dst_channel_id": "channel-165", "dst_port_id": "transfer"}
```

**Comment by mark-rushakoff** [comment]
The only way I can see not logging after a timeout, is if RelayPackets or RelayAcknowledgements returns nil when the context is canceled. I'll take a look through those code paths to see if it's possible we are hitting that.

**Comment by mark-rushakoff** [comment]
RelayMsgs.Send would swallow context errors. It should return an error. Or at least we could check the context error again in the caller.

**Comment by mark-rushakoff** [comment]
@jtieri give f8fa9e2d7f241ade212e7787516b77b552559fb2 a try.

**Review by jtieri — APPROVED** [review]
Looks good to me, tested again and logs are consistent.

**Pull request merged**
